### ISSUE TITLE
Error: spawn java ENOENT

### ISSUE THREAD

**Issue by vilius-rugaitis** [graphcool/serverless-plugin-typescript#37]
I have problems running the `sls offline start` command on a macOS Sierra 10.12.6. All files are generated correctly, but just before the start of the local web server, there is an error. In addition to that, the command `sls offline` runs correctly, but since the local dynamodb server is not automatically launched, it is not an option.

```
$ node --version
v6.11.0
```

```
$ npm --version
3.10.10
```

```
$ sls version
1.22.0
```

serverless.yml
```
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-browserifier
  - serverless-dynamodb-local
  - serverless-offline
```

tsconfig.json
```
{
  "compilerOptions": {
    "preserveConstEnums": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "target": "es5",
    "outDir": ".build",
    "moduleResolution": "node",
    "lib": ["es2015"],
    "rootDir": "./"
  }
}
```

Output
```
$ serverless offline start
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke offline:start
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Watching typescript files...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by vilius-rugaitis** [comment]
Problem was caused by the `dynamodb-local` plugin.[I somehow had to re-install the dynamodb instance](https://github.com/99xt/serverless-dynamodb-local/issues/127#issuecomment-326178154).
