### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined when trying to use individual packaging

### ISSUE THREAD

**Issue by KSuttle-cng** [graphcool/serverless-plugin-typescript#39]
Tried it this way
```yml
# global
package:
  individually: true
# ...
functions:
# ...
  stateDocuments:
      handler: src/Dispatcher.getStateDocuments
      package:
        include:
          - src/assets/**
```

and this way
```yml
# individual
  stateDocuments:
    package:
      individually: true
      include:
        - src/assets/stateDocuments/
```
With and without: `excludeDevDependencies: false`

```
$ serverless package --verbose
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command offline
Serverless: Load command offline:start

 Serverless Warning --------------------------------------

  A valid option to satisfy the declaration 'opt:stage' could not be found.

Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir

  Type Error ---------------------------------------------

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at TypeScriptPlugin.prepare (myproject/node_modules/serverless-plugin-typescript/dist/src/index.js:71:45)
    at TypeScriptPlugin.<anonymous> (myproject/node_modules/serverless-plugin-typescript/dist/src/index.js:100:18)
    at next (native)
    at myproject/node_modules/serverless-plugin-typescript/dist/src/index.js:7:71
    at __awaiter (myproject/node_modules/serverless-plugin-typescript/dist/src/index.js:3:12)
    at TypeScriptPlugin.compileTs (myproject/node_modules/serverless-plugin-typescript/dist/src/index.js:99:16)
    at BbPromise.reduce (/Users/ksuttle/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/Users/ksuttle/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/Users/ksuttle/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/Users/ksuttle/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/Users/ksuttle/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/Users/ksuttle/.nvm/versions/node/v6.11.0/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.11.0
     Serverless Version:     1.23.0
```

```json
"serverless-plugin-typescript": "^1.1.2",
```

If I have the package declaration at the top of the file, globally declared, it works fine, but then that directory and its contents are copied into every lambda function, which is not ideal.

**Comment by pjsier** [comment]
@KSuttle-cng This was the same error I was running into with #38. Your function package declarations only have `include`, and the plugin was either expecting them to be totally empty or have both `include` and `exclude`. Should be resolved now though with the latest version

**Comment by KSuttle-cng** [comment]
@pjsier Thanks. How do I get this to work until a new version is pushed?

**Comment by pjsier** [comment]
@KSuttle-cng the latest version on npm (1.1.3) has this change, so updating the package should fix it

**Comment by KSuttle-cng** [comment]
Thanks @pjsier. Appears to be working now, though I'm running into the speed issue mentioned here: https://github.com/serverless/serverless/issues/4263
