### ISSUE TITLE
sls package not working

### ISSUE THREAD

**Issue by vilius-rugaitis** [graphcool/serverless-plugin-typescript#40]
I have problems running the `sls package` command on a macOS Sierra 10.12.6 (actually the `sls deploy` command, but already the packaging is failing). During the execution, first the `.serverless` folder and than the `.build` folder are created. The problem is, that the `.serverless` folder should be part of the `.build` folder for the command to execute successfully. I have tested it and if I move the `.serverless` folder into the `.build` folder and re-run the `sls package` command, the packaging succeeds.

```
$ node --version
v6.11.0
```

```
$ npm --version
3.10.10
```

```
$ sls version
1.23.0
```

**package.json**
```
"dependencies": {
    "aws-sdk": "^2.122.0",
    "uuid": "^3.1.0"
  },
  "devDependencies": {
    "@types/node": "^8.0.30",
    "serverless-dynamodb-local": "^0.2.25",
    "serverless-offline": "^3.16.0",
    "serverless-plugin-browserifier": "^1.0.5",
    "serverless-plugin-typescript": "^1.1.2"
  }
```

**serverless.yml**
```
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-browserifier
  - serverless-dynamodb-local
  - serverless-offline
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "preserveConstEnums": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "sourceMap": true,
    "target": "es5",
    "outDir": ".build",
    "moduleResolution": "node",
    "lib": ["es2015"],
    "rootDir": "./"
  }
}
```

**Folder structure**
```
/
  .serverless -> 1st generated folder; **ERROR: should be part of the .build folder**
  .build -> 2nd generated folder; **ERROR: schould actually include the .serverless folder**
  node_modules
  entity
    get.ts
    [...]
  serverless.yml
  tsconfig.json
  package.json
```

**Error**
```
$ sls package
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command dynamodb
Serverless: Load command dynamodb:migrate
Serverless: Load command dynamodb:seed
Serverless: Load command dynamodb:start
Serverless: Load command dynamodb:noStart
Serverless: Load command dynamodb:remove
Serverless: Load command dynamodb:install
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
Serverless: Browserifier::validate
Serverless: Browserifier::globalConfig
computed globalBrowserifyConfig { disable: false,
  [...]
  debug: false }
Serverless: Browserifier: Preparing **entity**_list...
Serverless: Browserifier: Preparing **entity**_create...
Serverless: Browserifier: Preparing **entity**_get...
Serverless: Browserifier: Preparing **entity**_update...
Serverless: Browserifier: Preparing **entity**_delete...
Serverless: Packaging service...

  Error --------------------------------------------------

  ENOENT: no such file or directory, lstat '/Users/***/***/***/.build/.serverless'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, lstat '/Users/***/***/***/.build/.serverless'
    at Error (native)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
```

**Comment by vilius-rugaitis** [comment]
Removing `serverless-plugin-browserifier` resolved the issue. So, something has to be wrong with another plugin.

**Comment by kvarela** [comment]
Yeah, I'm having the same issue with serverless-plugin-browserifier and serverless-plugin-typescript. They both work fine on their own, but not together for some reason. Does anybody have any ideas?

I'm getting the same error:
```
Serverless: Browserifier: Created graphql.zip (11.18 MB)...

  Error --------------------------------------------------

  ENOENT: no such file or directory, lstat '/Users/home/roam/backend/.build/.serverless'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, lstat '/Users/home/roam/backend/.build/.serverless'
    at PluginManager.invoke (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.spawn (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:408:17)
    at Deploy.BbPromise.bind.then.then (/Users/home/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:118:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/Users/home/.config/yarn/global/node_modules/serverless/lib/plugins/deploy/deploy.js:113:10)
    at BbPromise.reduce (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:55)
From previous event:
    at PluginManager.invoke (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:390:22)
    at PluginManager.run (/Users/home/.config/yarn/global/node_modules/serverless/lib/classes/PluginManager.js:421:17)
    at variables.populateService.then.then (/Users/home/.config/yarn/global/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Serverless.run (/Users/home/.config/yarn/global/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/home/.config/yarn/global/node_modules/serverless/bin/serverless:43:50)
```
